### ISSUE TITLE
Reputation Point Rules + App Features

### ISSUE THREAD

**Issue by serapath** [wizardamigosinstitute/RepPointsServer#6]
# Summary from #1

_**Work in Progress** - please comment_
## Reputation Points Journal [RPJ]

https://github.com/wizardamigosinstitute/RepPointsServer/blob/master/data/dis_snapshot.json

> e.g. Nina and Myself started the wizard school in April/May this year, thought kids, created website + texts + logos, went around with lots of flyers and invested some energy into social media (twitter/facebook/blog/....) and even paid for domains, flyers, logo design on fiver.de. Then Yannis helped with a little re-design of the website and was brainstorming with us. With Alexej we know were co-organizing the CodeMotion Event and we built some marketing materials and concepts for activities we could do with kids + we brainstormed about how we could do the shares or co-ownership. Alexej now created a repository for the server (see above)
## Reputation Point Rules [RP]

The **`RP`** work a bit like shares in a company.
https://github.com/wizardamigosinstitute/RepPointsServer/blob/master/data/rules.json
### Point Creation Rate [CR]

We need a way to create new shares and a **`CR`** is one way of creating new shares. A **`CR`** is voted on by all users and determined choosing the median. It "waters down" the value of all points currently held by users, but allows for a "higher resolution" (more fine grained control) when transfering points to others. The change in ownership is calculated by dividing ones own points through the total amount of points which currently exist.
### Point Redistribution Rate [RR]

Everyone respecting **`RP`**'s of others is a service everyone offers and should be paid. A `Point Redistribution Rate` is setting the **service price** and is voted on by all users and determined choosing the median. The change in ownership is directly visible through the points people currently hold.

**Comment by serapath** [comment]
# Proposals
_Please everyone comment on refining your proposals or ask question to make proposals of others more clear._

* [ ] There should be a **"Voting System based on Reputation Points"**
* [ ] `Reputation Points` should be named `Respect Points`
* [ ] There should be a list of all users and their current amount of points
* [ ] It should be possible to transfer points to a user
* [ ] The current rules should be presented to the user
* [ ] Refactor all rules to be as simple and concise as possible, while still easy to understand.

### @Nasdneb
###### Rules
**1.** Everyone starts with 10 points
**2.** Redistribution: Redistribute 5% each day  
  * `Reasoning`: To have fast impact that helps to get a feeling for the mechanics, thus "how it works")  

**3.** Creation: Create 10 new points each week
**4.** Then everyone makes his list of activities, and we can distribute our points. (i guess the 10 points)

###### App
* ...

### @vysogot
###### Rules
* start with flatrate
* everyone gets 10 points
* only if you have 0 points you will get a UBI (Unconditional Basic Income)
* When there is "income", all "organization costs" (e.g. materials, rents, ...) are substracted, then distribution starts.
* brainstorming doesnt count as "organization costs" and not as "activity"
* "good ideas" from brainstorming can count as "activity" (e.g. algorithm/event/game/video ABC)
* renaming "reputation points" to "respect points"
* ```bash
  UBI = revenue * 33% / number of people
  surplus = revenue - UBI
  pay = UBI + personPoints/totalPoints*surplus
  ```

###### App
* named column for each person
* below a list of tasks/activities that were accomplished
* items are linked if done together with others
* button where everyone can click to spend points to a certain activity
  * if done by many, it's distributed evenly about all contributors

### @derhuerst
###### Rules
* ...

###### App
* ...

### @ninabreznik
###### Rules
* ...

###### App
* ...

### @serapath
###### Rules
* There needs to be a high motivation for people to actually earn the cake that we want to distribute.
* People who join can never be kicked out
* If somebody is not happy he should create his *organizational fork* and may invite others to join and continue on his/her/their own with the new organization.
* I want a **`RR`** as described above
* I want a **`CR`** as described above
* I want a **`RPJ`** as described above

###### App
* ...

**Comment by serapath** [comment]
# Questions
* How can we change rules in the future? (from @serapath to @all)
* Which process can switch an existing organization to use the methods described here? (from @serapath to @all)
* Why would i ever vote for an activity of others, if i spend votes that would otherwise give me revenue... i don't feel like motivated to vote a lot - i guess i would be rather lazy or only vote as much as the person that gives the least amount of votes. (from @serapath to @all)

**Comment by ninabreznik** [comment]
Great job, went through everything and really sorry I didn't manage to join in before, but I still have my dad here and we're still fixing our flat (which was completely empty when we came).

Ok, to the point now.

**Things that are blurry in my head and can't be put into anything concrete yet:**
- I want to make pros/cons for options
  We each earn her/his own money with our workshops for kids and put 
  a) all the money on the pile and then redistribute it (we work as a team and not only "earners" matter)
  b) put % of our earnings on the pile and redistribute that (each is accountable for his earnings, but we put (i.e. 50%) into the greed and then redistribute that). Probably this is the better option but just didn't go through all ifs of both options yet...

### Creation rate
- I see that if we just create 10 new points for each member each month we are actually rewarding seniority (older members are worth more than newer). 
- **Problem** I see here: what if new member invests all his time and old member is just here on the side for the long time, but doesn't really contribute.
- **Suggestion**: maybe (i.e.) 100 points could be created each month and they would be divided by the Respect Points (if x has 1200 RP and y 600 RP, then 100 new points: 2/3 for x and 1/3 for y). In this case we would reward the ones that contribute most and not the ones that are there longest.

### Redistribution
- I like the idea that we just reward the projects we support.
- **Suggestion**:  We need to have a common strategy/agreement what we want to reward. Otherwise it can easily happen that we just give back points to someone who gave them to us or we just randomly reward some tasks that sound nice to us (specially if tasks are more technical: i.e. someone is working on accounting things or some server stuff or some marketing strategy - because we don't all understand everything) and then the whole "game" loses its purpose.  
- **UBI**: When I think of it, I imagine, there should be a minimum income for every member. If we say each should get at least 300 each month, then we each get equal shares until we reach this amount and then afterwards we divide based on RespectPoints. Example: it is 5 of us and we got in 1000€. We divide this on equal 200€ incomes. Second example - we got in 2000. Each gets 300 (300x5 = 1500; 2000-1500 = 500) and 500 we split based on ReputationPoints (those who are higher on the ladder get more). 
- **Ladder**
  We give each other each week points for tasks we do for Wizard Amigos Institute. As said before we need some common strategy to see where we are trying to get with the project ( I can at least say for marketing that if we just communicate a bit here, a bit there, result is way weaker than if we make a strategy and do stuff synchronised and in the right time and connected with other communication activities).
  Maybe we could also give points when tasks are offered (in advance) so each can see and explain why she/he thinks this is important. Then if someone sees there is no interest, she/he can rethink if this is really a priority (synched with the strategy) and is not angry/sad after she/he invested lots of her/his time into it. And after the task we could then confirm the points and could have a possibility to give +- 30% of points we gave in advance (if task was poorly done or if it didn't bring us results we were hoping for, we give less, otherwise same or more).

Ok, I will update this later, but just to put first thoughts out finally :)

**Comment by serapath** [comment]
@ninabreznik 

#### Earnings:
Given a new teacher comes in and teaches his first lesson, that would earn him little, but the more time he invests, the more points he gains and so his "dividend" increases over time. So, a new teacher has to build up his "reputation first" and in the beginning he earns more like a volunteer or intern.
* I propose a thought lesson earn you points - like other activities
* Money paid by learners or their representatives is distributed according to the points

#### Creation Rate:
An old member might also loose points through the "redistribution rate", while a very active new member might constantly gain points from activities on top of what he gets through the creation rate. Initially he will even earn points from the redistribution rate, because he starts out with less than average points.

* **Question:** Does that solve the "problem"?

I wouldn't go with your suggestion, because the `Redistribution Rate` might already do what you suggest.

* **Question:** Do you think so too?

#### Redistribution Rate:
I agree that we need some mechanism to decide how many points we give for certain activities and we might need even have different mechanisms for that, e.g.:
**Proposal:**
1. `pledge` => for example: i give 10 points if everyone else gives 10 points too
2. `kickstarter` => Everyone can give points and something gets done when A points are reached
3. `wish` => I give B points to everyone that does a certain task i propose
  * maybe I can add that after the task is finished I am allowed to give B+/-`reward` instead of B

Every `pledge`/`kickstarter`/`wish` could be a one time thing, or a re-occuring thing. It's basically a set of "standard contracts" through wish we can interact and we can improve and change our `standard templates` for such contracts - above I proposed 3.

... maybe we need more or less than that.

##### UBI
> hen we each get equal shares until we reach this amount and then afterwards we divide based on RespectPoints.

I don't like it.  
For me, the **UBI** is defined by the `Redistribution Rate`, so if we feel like a high **UBI** is a good thing, we set a high `Redistribution Rate`. If we feel people are abusing it too much, we vote on a lower `Redistribution Rate`. This feels to me like a very simple mechanism and if you feel the same, we should add this **"functionality"** to the description of the `Redistribution Rate`

##### Ladder
For **"The Past"** we need a **"One Time Solution"** to account for what has already been done.
In general and for everyone who starts a new organization or project with the rules we discuss here, this problem might be solved by using something like the proposal i made above (e.g. `kickstarter`, `pledge`, `wish`)

**Comment by serapath** [comment]
Added to SPECIFICATION/README.md in upcoming pull request -> please discuss it there.

**UPDATE:**
The latest updates are to be found here: https://github.com/wizardamigosinstitute/RepPointsServer/pull/9
